[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "fastapi-todo-app"
version = "0.0.1"
requires-python = ">=3.11"
description = "FastAPI ToDo sample"
