name: CI-E2E (Postgres + coverage)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: todo_ci
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@localhost:5432/todo_ci

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: .
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run pytest (includes E2E, with coverage)
        working-directory: .
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: pytest -q

      - name: Upload coverage to Codecov (e2e)
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: e2e
          fail_ci_if_error: true
          verbose: true
